CREATE TABLE OFFICE2(
ID NUMBER(10),
EMPLOYEE_NAME VARCHAR2(50));
INSERT INTO OFFICE2(ID,EMPLOYEE_NAME)
VALUES(1,'ASKANI');
INSERT INTO OFFICE2(ID,EMPLOYEE_NAME)
VALUES(2,'GAUTHAM');
INSERT INTO OFFICE2(ID,EMPLOYEE_NAME)
VALUES(3,'SUSHMITA');
INSERT INTO OFFICE2(ID,EMPLOYEE_NAME)
VALUES(4,'DEEKSHITA');

SELECT * FROM OFFICE2;
